# Twitter API keys
CONSUMER_KEY = 'CONSUMERKEY'
CONSUMER_SECRET = 'CONSUMERSECRET'
ACCESS_TOKEN_KEY = 'ACCESSTOKENKEY'
ACCESS_TOKEN_SECRET = 'ACCESSTOKENSECRET'

# Database path
DB_PATH = '/path/to/your/db'
